### ISSUE TITLE
Utilização da linha de comando para criação dos grupos

### ISSUE THREAD

**Issue by carlsonsantana** [andersonqueiroz/frequencia#2]
Na documentação deste projeto esta informando que para utilizar o sistema se faz necessário executar o comando:

```shell
python ./manage.py instalacao
```

Acredito que seria melhor [escrever um migrador](https://docs.djangoproject.com/pt-br/2.2/howto/writing-migrations/), para que os grupos fossem criados quando o usuário executasse o comando para executar a migração através do comando:
```shell
python manage.py migrate
```

**Comment by andersonqueiroz** [comment]
Oi Carlos, obrigado pela contribuição. Realmente um migrador é a solução mais elegante e evitaria um passo a mais no momento da instalação.

Vou colocar essa tarefa na fila de implementação.
